### ISSUE TITLE
Conversion error when using filled white path in svg

### ISSUE THREAD

**Issue by hungerpirat** [mrbeam/OctoPrint#88]
from the logs:
'''
2016-11-11 14:15:54,788 - octoprint.plugins.svgtogcode.engine - INFO - ### Slicing /home/pi/.octoprint/uploads/local/temp.svg to /tmp/tmpC_P_qq.gco using profile stored at /tmp/slicing-profile-temp-WD6tSx.profile
2016-11-11 14:15:58,984 - octoprint.plugins.mrbeam - ERROR - Conversion error (Mapping key not found.): #FFFFFF
Traceback (most recent call last):
  File "/home/pi/MrBeamPlugin/octoprint_mrbeam/__init__.py", line 572, in do_slice
    engine.affect(on_progress, on_progress_args, on_progress_kwargs)
  File "/home/pi/MrBeamPlugin/octoprint_mrbeam/gcodegenerator/inkex.py", line 268, in affect
    self.effect(on_progress, on_progress_args, on_progress_kwargs)
  File "/home/pi/MrBeamPlugin/octoprint_mrbeam/gcodegenerator/mrbeam.py", line 3533, in effect
    self.laser(on_progress, on_progress_args, on_progress_kwargs)
  File "/home/pi/MrBeamPlugin/octoprint_mrbeam/gcodegenerator/mrbeam.py", line 3316, in laser
    gcode_outlines += "; Layer: " + layerId + ", outline of " + pathId + ", stroke: " + colorKey +', '+str(self.colorSettings[colorKey])+"\n"
KeyError: '#FFFFFF'
2016-11-11 14:15:58,986 - octoprint.plugins.svgtogcode.engine - INFO - ----------------------------------------
'''

**Comment by clemniem** [comment]
fixed
